name: Build Strombreaker KSU Next Surya
on:
  push:
    branches: [ "Sbv8ksun" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Alat Kerja + Install Clang Resmi Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential libncurses5-dev libssl-dev bison flex libelf-dev clang-14 lld-14 git rsync llvm-14 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Ambil Source Strombreaker Lo
        run: |
          git clone --depth=1 https://github.com/kiwan5181-ops/Sbv8ksun.git -b Sbv8ksun kernel-source

      - name: Pasang KernelSU Next (Metode Symlink Murni)
        run: |
          cd kernel-source
          # 1. Clone repositori utuh ke folder KernelSU-Next di root
          git clone --depth=1 https://github.com/rifsxd/KernelSU-Next.git KernelSU-Next
          
          # 2. Buat hubungan (symlink) sub-folder kernel-nya ke drivers/kernelsu secara rapi
          ln -s "$(pwd)/KernelSU-Next/kernel" "$(pwd)/drivers/kernelsu"
          
          # 3. Daftarkan ke drivers/Makefile utama kernel
          echo "obj-y += kernelsu/" >> drivers/Makefile

      - name: Aktifkan KSU Next ke Surya Defconfig
        run: |
          cd kernel-source
          echo "CONFIG_KSU=y" >> arch/arm64/configs/surya-perf_defconfig
          echo "CONFIG_KSU_NEXT=y" >> arch/arm64/configs/surya-perf_defconfig
          echo "CONFIG_OVERLAY_FS=y" >> arch/arm64/configs/surya-perf_defconfig

      - name: Proses Masak Kernel (Murni Lokal Server)
        run: |
          cd kernel-source
          export ARCH=arm64
          export SUBARCH=arm64
          export HEADER_ARCH=arm64
          
          make O=out ARCH=arm64 surya-perf_defconfig
          make O=out ARCH=arm64 CC=clang-14 LD=ld.lld-14 AR=llvm-ar-14 NM=llvm-nm-14 OBJCOPY=llvm-objcopy-14 OBJDUMP=llvm-objdump-14 STRIP=llvm-strip-14 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- -j$(nproc --all)

      - name: Ambil Hasil Jadi (Image.gz-dtb)
        uses: actions/upload-artifact@v4
        with:
          name: Strombreaker-Surya-KSUNext
          path: |
            kernel-source/out/arch/arm64/boot/Image.gz-dtb
            kernel-source/out/arch/arm64/boot/Image.gz
            kernel-source/out/arch/arm64/boot/Image
