name: Build Strombreaker KSU Next Surya
on:
  push:
    branches: [ "Sbv8ksun" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Alat Kerja + Install Clang Resmi Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential libncurses5-dev libssl-dev bison flex libelf-dev clang-14 lld-14 git rsync llvm-14 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Ambil Source Strombreaker Lo
        run: |
          git clone --depth=1 https://github.com/kiwan5181-ops/Sbv8ksun.git -b Sbv8ksun kernel-source

      - name: Inject KSU Next Jalur Resmi Komunitas (Legacy Branch)
        run: |
          cd kernel-source
          # Menggunakan skrip resmi KSU-Next khusus untuk kernel tua (4.14 non-GKI)
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/main/kernel/setup.sh" | bash -s legacy

      - name: Aktifkan KSU ke Surya Defconfig
        run: |
          cd kernel-source
          # Mengaktifkan benderanya di config Poco X3 NFC lo
          echo "CONFIG_KSU=y" >> arch/arm64/configs/surya-perf_defconfig
          echo "CONFIG_KSU_NEXT=y" >> arch/arm64/configs/surya-perf_defconfig

      - name: Proses Masak Kernel
        run: |
          cd kernel-source
          export ARCH=arm64
          export SUBARCH=arm64
          export HEADER_ARCH=arm64
          
          make O=out ARCH=arm64 surya-perf_defconfig
          make O=out ARCH=arm64 CC=clang-14 LD=ld.lld-14 AR=llvm-ar-14 NM=llvm-nm-14 OBJCOPY=llvm-objcopy-14 OBJDUMP=llvm-objdump-14 STRIP=llvm-strip-14 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- -j$(nproc --all)

      - name: Ambil Hasil Jadi (Image.gz-dtb)
        uses: actions/upload-artifact@v4
        with:
          name: Strombreaker-Surya-KSUNext
          path: |
            kernel-source/out/arch/arm64/boot/Image.gz-dtb
            kernel-source/out/arch/arm64/boot/Image.gz
            kernel-source/out/arch/arm64/boot/Image
